# Generated by Django 3.2.13 on 2022-04-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('description', models.TextField()),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('category', models.CharField(choices=[('P', 'Poussin'), ('E', 'Ecole'), ('B', 'Benjamin'), ('M', 'Minime'), ('C', 'Cadets'), ('J', 'Junior'), ('S', 'Senior')], max_length=1)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esm.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('description', models.TextField()),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='esm.groupe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
