# Generated by Django 3.2.13 on 2022-04-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='esm/static/img/'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='esm/static/img/'),
        ),
    ]
