# Generated by Django 3.2.13 on 2022-04-13 01:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0003_auto_20220412_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('scan_1', models.ImageField(upload_to='')),
                ('scan_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('scan_3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
