# Generated by Django 3.2.13 on 2022-04-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0005_auto_20220413_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
