# Generated by Django 3.2.13 on 2022-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0008_auto_20220413_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='type_event',
            field=models.CharField(choices=[('C', 'Competition'), ('B', 'Blog'), ('N', 'Actualités')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualités/'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profilephoto/'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profilephoto/'),
        ),
    ]
