# Generated by Django 3.2.13 on 2022-05-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0009_auto_20220501_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode_inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
    ]
