# Generated by Django 3.2.13 on 2022-05-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0010_periode_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='periode_inscription',
            name='debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='periode_inscription',
            name='fin',
            field=models.DateTimeField(),
        ),
    ]
