# Generated by Django 3.2.13 on 2022-05-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0011_auto_20220504_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gallery_photo',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
