# Generated by Django 3.2.13 on 2022-05-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0012_auto_20220506_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
