# Generated by Django 3.2.13 on 2022-05-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0015_alter_inscription_scan_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='scan_1',
            field=models.ImageField(upload_to='esm/static/img/inscriptions/'),
        ),
    ]
