# Generated by Django 3.2.13 on 2022-05-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0016_alter_inscription_scan_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
