# Generated by Django 3.2.13 on 2022-05-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0018_auto_20220507_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=10000)),
            ],
        ),
    ]
