# Generated by Django 3.2.13 on 2022-05-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0019_message_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='inscription',
            name='athlete',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='esm.athlete'),
            preserve_default=False,
        ),
    ]
