# Generated by Django 3.2.13 on 2022-05-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0020_auto_20220513_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='athlete',
        ),
    ]
