# Generated by Django 3.2.13 on 2022-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0022_auto_20220513_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='afficher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='inscrit',
            field=models.BooleanField(default=False),
        ),
    ]
