# Generated by Django 3.2.13 on 2022-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0023_auto_20220513_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='scan_1',
            field=models.ImageField(upload_to='inscriptions/extrait-naissance/'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='scan_2',
            field=models.ImageField(blank=True, null=True, upload_to='inscriptions/scans-2/'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='scan_3',
            field=models.ImageField(blank=True, null=True, upload_to='inscriptions/scans-3/'),
        ),
    ]
