# Generated by Django 3.2.13 on 2022-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0024_auto_20220513_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
