# Generated by Django 3.2.13 on 2022-05-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0025_alter_inscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_photo',
            name='image',
            field=models.ImageField(upload_to='galerie/'),
        ),
    ]
