# Generated by Django 3.2.13 on 2022-05-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0026_alter_gallery_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_photo',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gallery_photo',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
