# Generated by Django 3.2.13 on 2022-05-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0027_auto_20220513_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_photo',
            name='title',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
