# Generated by Django 3.2.13 on 2022-05-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0028_alter_gallery_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_photo',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
