# Generated by Django 3.2.13 on 2022-05-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0029_alter_gallery_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='scan_2',
            field=models.ImageField(upload_to='inscriptions/scans-2/'),
        ),
    ]
