# Generated by Django 3.2.13 on 2022-05-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esm', '0030_auto_20220513_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='accepted',
        ),
    ]
